version: 2
registries:
  jsr:
    type: npm-registry
    url: https://npm.jsr.io

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    registries:
      - jsr

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
